

export class PlanetActions{
    static FETCH_PLANET_LIST = 'FETCH_PLANET_LIST';
    static FETCH_PLANET_LIST_SUCCESS = 'FETCH_PLANET_LIST_SUCCESS';
    static FETCH_PLANET_LIST_FAILURE = 'FETCH_PLANET_LIST_FAILURE';
}